library("ggplot2")

setwd("chr_CSV")
chr1<-read.csv("chr_CSV/chr1.csv")
p <- ggplot(chr1, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.1, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0, 100, by = 10), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0, 110, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr1") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr1.png")
ggsave("chr1.png")

chr2<-read.csv("chr_CSV/chr2.csv")
#chr2$Genome <- rev(chr2$Genome)
p <- ggplot(chr2, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0, 60, by = 5), sec.axis = sec_axis(~.*1.0, name = "Estimated SNP distance (Mbp)", breaks=seq(0,60, by = 5)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
#p <- p +scale_x_discrete(limits = rev(levels(the_factor), name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5)))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr2") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p
unlink("chr2.png")
ggsave("chr2.png")

chr3<-read.csv("chr_CSV/chr3.csv")
p <- ggplot(chr3, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.13, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0, 70, by = 5), sec.axis = sec_axis(~.*0.86, name = "Estimated SNP distance (Mbp)", breaks=seq(0,60, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0, 80, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr3") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr3.png")
ggsave("chr3.png")


setwd("chr_CSV")
chr4<-read.csv("chr_CSV/chr4.csv")
p <- ggplot(chr4, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.27, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0, 90, by = 10), sec.axis = sec_axis(~.*0.778, name = "Estimated SNP distance (Mbp)", breaks=seq(0,70, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0, 90, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr4") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr4.png")
ggsave("chr4.png")


setwd("chr_CSV")
chr5<-read.csv("chr_CSV/chr5.csv")
p <- ggplot(chr5, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*0.97, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0, 140, by = 10), sec.axis = sec_axis(~.*1.0, name = "Estimated SNP distance (Mbp)", breaks=seq(0,140, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0, 180, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr5") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr5.png")
ggsave("chr5.png")

setwd("chr_CSV")
chr6<-read.csv("chr_CSV/chr6.csv")
#chr6$Genome <- rev(chr6$Genome)
p <- ggplot(chr6, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.14, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,70, by = 5), sec.axis = sec_axis(~.*0.85, name = "Estimated SNP distance (Mbp)", breaks=seq(0,60, by = 5)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 10))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr6") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr6.png")
ggsave("chr6.png")

setwd("chr_CSV")
chr7<-read.csv("chr_CSV/chr7.csv")
p <- ggplot(chr7, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.16, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,70, by = 5), sec.axis = sec_axis(~.*0.85, name = "Estimated SNP distance (Mbp)", breaks=seq(0,60, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr7") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr7.png")
ggsave("chr7.png")

setwd("chr_CSV")
chr8<-read.csv("chr_CSV/chr8.csv")
#chr8$Genome <- rev(chr8$Genome)
p <- ggplot(chr8, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.13, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,70, by = 5), sec.axis = sec_axis(~.*0.86, name = "Estimated SNP distance (Mbp)", breaks=seq(0,60, by = 5)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,60, by = 5))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,60, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr8") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr8.png")
ggsave("chr8.png")

setwd("chr_CSV")
chr9<-read.csv("chr_CSV/chr9.csv")
p <- ggplot(chr9, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,120, by = 10), sec.axis = sec_axis(~.*1.0, name = "Estimated SNP distance (Mbp)", breaks=seq(0,120, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,150, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr9") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr9.png")
ggsave("chr9.png")


setwd("chr_CSV")
chr10<-read.csv("chr_CSV/chr10.csv")
p <- ggplot(chr10, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.2, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,70, by = 5), sec.axis = sec_axis(~.*0.82, name = "Estimated SNP distance (Mbp)", breaks=seq(0,50, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,60, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr10") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr10.png")
ggsave("chr10.png")

setwd("chr_CSV")
chr11<-read.csv("chr_CSV/chr11.csv")
#chr11$Genome <- rev(chr11$Genome)
p <- ggplot(chr11, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.05, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,120, by = 10), sec.axis = sec_axis(~.*0.94, name = "Estimated SNP distance (Mbp)", breaks=seq(0,110, by = 10)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,140, by = 10))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,140, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr11") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr11.png")
ggsave("chr11.png")

setwd("chr_CSV")
chr12<-read.csv("chr_CSV/chr12.csv")
#chr12$Genome <- rev(chr12$Genome)
p <- ggplot(chr12, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.08, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,120, by = 10), sec.axis = sec_axis(~.*0.92, name = "Estimated SNP distance (Mbp)", breaks=seq(0,110, by = 10)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,130, by = 10))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,130, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr12") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr12.png")
ggsave("chr12.png")

setwd("chr_CSV")
chr13<-read.csv("chr_CSV/chr13.csv")
p <- ggplot(chr13, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.12, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,90, by = 5), sec.axis = sec_axis(~.*0.89, name = "Estimated SNP distance (Mbp)", breaks=seq(0,80, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,90, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr13") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr13.png")
ggsave("chr13.png")

setwd("chr_CSV")
chr14<-read.csv("chr_CSV/chr14.csv")
p <- ggplot(chr14, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.1, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,100, by = 10), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,110, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr14") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr14.png")
ggsave("chr14.png")

setwd("chr_CSV")
chr15<-read.csv("chr_CSV/chr15.csv")
p <- ggplot(chr15, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.09, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,110, by = 10), sec.axis = sec_axis(~.*0.91, name = "Estimated SNP distance (Mbp)", breaks=seq(0,100, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,130, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr15") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr15.png")
ggsave("chr15.png")

setwd("chr_CSV")
chr16<-read.csv("chr_CSV/chr16.csv")
p <- ggplot(chr16, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.17, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,60, by = 5), sec.axis = sec_axis(~.*0.86, name = "Estimated SNP distance (Mbp)", breaks=seq(0,70, by = 5)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,130, by = 10))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,60, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr16") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr16.png")
ggsave("chr16.png")

setwd("chr_CSV")
chr17<-read.csv("chr_CSV/chr17.csv")
p <- ggplot(chr17, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.1, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,70, by = 5), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,80, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,80, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,60, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr17") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr17.png")
ggsave("chr17.png")

setwd("chr_CSV")
chr18<-read.csv("chr_CSV/chr18.csv")
p <- ggplot(chr18, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*0.92, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,140, by = 10), sec.axis = sec_axis(~.*1.08, name = "Estimated SNP distance (Mbp)", breaks=seq(0,130, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,160, by = 10))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,60, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr18") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr18.png")
ggsave("chr18.png")

setwd("chr_CSV")
chr19<-read.csv("chr_CSV/chr19.csv")
p <- ggplot(chr19, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.05, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,120, by = 10), sec.axis = sec_axis(~.*0.92, name = "Estimated SNP distance (Mbp)", breaks=seq(0,110, by = 10)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,110, by = 10))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,140, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr19") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr19.png")
ggsave("chr19.png")


setwd("chr_CSV")
chr20<-read.csv("chr_CSV/chr20.csv")
p <- ggplot(chr20, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.03, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,130, by = 10), sec.axis = sec_axis(~.*0.94, name = "Estimated SNP distance (Mbp)", breaks=seq(0,140, by = 10)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,160, by = 10))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,140, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr20") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr20.png")
ggsave("chr20.png")

setwd("chr_CSV")
chr21<-read.csv("chr_CSV/chr21.csv")
p <- ggplot(chr21, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.1, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,100, by = 5), sec.axis = sec_axis(~.*0.91, name = "Estimated SNP distance (Mbp)", breaks=seq(0,110, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,160, by = 10))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,110, by = 10))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr21") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr21.png")
ggsave("chr21.png")

setwd("chr_CSV")
chr22<-read.csv("chr_CSV/chr22.csv")
p <- ggplot(chr22, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.12, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,90, by = 5), sec.axis = sec_axis(~.*0.89, name = "Estimated SNP distance (Mbp)", breaks=seq(0,80, by = 5)))
#p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,160, by = 10))
p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr22") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr22.png")
ggsave("chr22.png")

setwd("chr_CSV")
chr23<-read.csv("chr_CSV/chr23.csv")
p <- ggplot(chr23, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.19, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,120, by = 5), sec.axis = sec_axis(~.*0.84, name = "Estimated SNP distance (Mbp)", breaks=seq(0,100, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,120, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr23") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr23.png")
ggsave("chr23.png")

setwd("chr_CSV")
chr24<-read.csv("chr_CSV/chr24.csv")
p <- ggplot(chr24, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.12, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,90, by = 5), sec.axis = sec_axis(~.*0.89, name = "Estimated SNP distance (Mbp)", breaks=seq(0,80, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,90, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr24") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr24.png")
ggsave("chr24.png")

setwd("chr_CSV")
chr25<-read.csv("chr_CSV/chr25.csv")
p <- ggplot(chr25, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.1, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,100, by = 5), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,110, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr25") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr25.png")
ggsave("chr25.png")

setwd("chr_CSV")
chr26<-read.csv("chr_CSV/chr26.csv")
p <- ggplot(chr26, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.16, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,70, by = 5), sec.axis = sec_axis(~.*0.86, name = "Estimated SNP distance (Mbp)", breaks=seq(0,60, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr26") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr26.png")
ggsave("chr26.png")

setwd("chr_CSV")
chr27<-read.csv("chr_CSV/chr27.csv")
p <- ggplot(chr27, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.15, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,90, by = 5), sec.axis = sec_axis(~.*0.86, name = "Estimated SNP distance (Mbp)", breaks=seq(0,80, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,90, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr27") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr27.png")
ggsave("chr27.png")

setwd("chr_CSV")
chr28<-read.csv("chr_CSV/chr28.csv")
p <- ggplot(chr28, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,80, by = 5), sec.axis = sec_axis(~.*1.0, name = "Estimated SNP distance (Mbp)", breaks=seq(0,80, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,80, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr28") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr28.png")
ggsave("chr28.png")

setwd("chr_CSV")
chr29<-read.csv("chr_CSV/chr29.csv")
p <- ggplot(chr29, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,80, by = 5), sec.axis = sec_axis(~.*1.0, name = "Estimated SNP distance (Mbp)", breaks=seq(0,80, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,90, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr29") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr29.png")
ggsave("chr29.png")

setwd("chr_CSV")
chr30<-read.csv("chr_CSV/chr30.csv")
p <- ggplot(chr30, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,110, by = 5), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,120, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr30") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr30.png")
ggsave("chr30.png")


setwd("chr_CSV")
chr31<-read.csv("chr_CSV/chr31.csv")
p <- ggplot(chr31, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,110, by = 5), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,120, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr31") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr31.png")
ggsave("chr31.png")



setwd("chr_CSV")
chr32<-read.csv("chr_CSV/chr32.csv")
p <- ggplot(chr32, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,110, by = 5), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,120, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr32") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr32.png")
ggsave("chr32.png")



setwd("chr_CSV")
chr33<-read.csv("chr_CSV/chr33.csv")
p <- ggplot(chr33, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,110, by = 5), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,120, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chr33") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chr33.png")
ggsave("chr33.png")



setwd("chr_CSV")
chrX<-read.csv("chr_CSV/chrx.csv")
p <- ggplot(chrX, aes(Genome, y = value, color = variable))
p <- p + geom_point(aes(y = f_cM, col = "Hind SNP marker (cM)"))
p <- p + geom_point(aes(y = m_cM, col = "Stag SNP marker (cM)"))
p <- p + geom_point(aes(y = Est_Mbp*1.0, col = "Estimated SNP marker (Mbp)"))
p <- p + scale_y_continuous(name = "Genetic map distance (cM)", breaks=seq(0,110, by = 5), sec.axis = sec_axis(~.*0.9, name = "Estimated SNP distance (Mbp)", breaks=seq(0,90, by = 5)))
p <- p + scale_x_continuous(name = "CerEla1.0 (Mbp)", breaks=seq(0,120, by = 5))
#p <- p +scale_x_reverse(name = "CerEla1.0 (Mbp)", breaks=seq(0,70, by = 5))
p <- p + scale_colour_manual(values = c("green", "blue", "red"))
p <- p + theme_bw()
p <- p + theme_classic()
p <- print(p + ggtitle("Ce chrX") + theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold")))
p <- p + theme(axis.title.x = element_text(color="black", size = 14, face = "bold" ), axis.title.y = element_text(color="black", size = 14, face = "bold"))
p <- p + theme(legend.text=element_text(size=11))
p <- p + coord_fixed(ratio = 1)
p

unlink("chrx.png")
ggsave("chrx.png")